[package]
name = "megaeth-validator"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "megaeth-validator"
path = "src/main.rs"

[dependencies]
alloy-primitives.workspace = true
alloy-provider.workspace = true
alloy-rpc-types-eth.workspace = true

revm = { workspace = true, features = ["serde"] }

salt.workspace = true

bincode.workspace = true
clap.workspace = true
eyre.workspace = true
futures.workspace = true
jsonrpsee.workspace = true
num_cpus.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
validate = { path = "../../validate" }

[dev-dependencies]
jsonrpsee-types.workspace = true
op-alloy-rpc-types.workspace = true
