[package]
name = "witness-decoder"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy-primitives = { workspace = true }
bincode = { workspace = true }
blake3 = { workspace = true }
clap = { workspace = true, features = ["derive"] }
eyre = { workspace = true }
hex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
validator-core = { path = "../../validator-core" }
