[package]
name = "stateless-validator"
version = "2.0.4"
edition = "2024"

[[bin]]
name = "stateless-validator"
path = "src/main.rs"

[dependencies]
# alloy
alloy-genesis.workspace = true
alloy-primitives.workspace = true
alloy-provider.workspace = true
alloy-rpc-types-eth.workspace = true

# op
op-alloy-network.workspace = true
op-alloy-rpc-types.workspace = true

# revm
revm = { workspace = true, features = ["serde"] }

# megaeth 
salt.workspace = true

# misc
bincode.workspace = true
clap = { workspace = true, features = ["env"] }
eyre.workspace = true
futures.workspace = true
metrics.workspace = true
metrics-exporter-prometheus.workspace = true
num_cpus.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tracing-appender.workspace = true
validator-core = { path = "../../validator-core" }

[dev-dependencies]
jsonrpsee = { version = "0.26", features = ["server", "macros"] }
jsonrpsee-types = { version = "0.26" }
tempfile = "3.8"

[features]
test-bucket-resize = ["salt/test-bucket-resize", "validator-core/test-bucket-resize"]