name: lint
on:
  workflow_call:
  workflow_dispatch:
  pull_request:

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  clippy:
    name: clippy
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_GAO_CI }}
      - name: Configure Git credentials
        uses: ./.github/actions/git_config
        with:
          github_pat: ${{ secrets.PAT_GAO_CI }}
      # parse tool chain file to get version, and integrate rust cache action
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        # with:
        #   # default is -D warnings
        #   rustflags: "-A warnings"
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - run: cargo clippy

  fmt:
    name: fmt
    runs-on: ubuntu-24.04
    continue-on-error: true
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git credentials
        uses: ./.github/actions/git_config
        with:
          github_pat: ${{ secrets.PAT_GAO_CI }}
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - run: cargo fmt --all --check
        name: code format

  codespell:
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: codespell-project/actions-codespell@v2
#   security_audit:
#     runs-on: ubuntu-24.04
#     steps:
#       - uses: actions/checkout@v4
#         with:
#           token: ${{ secrets.PAT_GAO_CI }}
#       - uses: rustsec/audit-check@v2.0.0
#         with:
#           token: ${{ secrets.PAT_GAO_CI }}
